### PR TITLE
Update composer.json for phpcs 2.3

### PR DESCRIPTION
**Pull request by JEDIBC**

### CODE REVIEW

**Comment by mikaelrandy** [comment]
:+1: for me, but as this upgrade does a major upgrade of CodeSniffer, i will release it as major version here too.

In my own case, this upgrade will break [Symfony2-coding-standard](https://github.com/M6Web/Symfony2-coding-standard)'s integration

**Comment by mikaelrandy** [comment]
v2.0.0

**Comment by JEDIBC** [comment]
How to make https://github.com/M6Web/Symfony2-coding-standard compliant with this phpcs version ?

**Comment by mikaelrandy** [comment]
It's seems to be a big refactoring work as the PHPCS 2's interfaces seems to be completely different.

**Pull request merged**
